### ISSUE TITLE
Create enum to allow either Promise<T, E> or Result<T, E> to be returned from a closure

### ISSUE THREAD

**Issue by jnicholls** [bcndanos/asynchronous#1]
Right now the promise closure must return only a Result<T, E> type, which makes it clunky to chain promise handlers together.  A coherent promise implementation allows one to return a value or another promise, and when a continuation is done on the outer promise, it is continuing on the inner promise that was returned.

I suggest creating an enum type for the return type of all the methods, that can be either another Promise<T, E> type or be a Result<T, E> type.  I have no idea if Rust's type system will get in the way here, or type inference will fail miserably...but this is the first thing that comes to my mind when thinking about solving the problem.

**Comment by bcndanos** [comment]
Hello!! Thanks for your comment.
I thought much about it. At the begining I had a enum as you say. But, I preferred return a 'Result',  that way you can use 'try!', and it's more clear.
One way to chain promises with different type results is:

fn promise_return_string() -> Promise<String,()> {
   Promise::new(|| {
      // Do something
      Ok("Value".to_string())
  })
}

fn promise_return_u32(num:u32) -> Promise<u32,()> {
   Promise::new(|| {
      // Do something
      Ok(num \* 2)
   })
}

fn promise_return_u64(num:u32) -> Promise<u64,()> {
   Promise::new(|| {
      // Do something
      Ok(num as u64 \* 3)
   })
}

fn main() {
   promise_return_string()
   .then(|res| {
      assert_eq!(res, "Value");
      promise_return_u32(7).sync()    <- You have to use 'sync' for chain these promises
   }, |err| {
      // Cath the error, and / or propagate
      Err(err)
   }).success(|res| {   // It's the same as 'then' but only catches the Result OK, The Err is propagated.
     assert_eq!(res, 14u32);
     promise_return_u64(res).sync()
   }).

}

**Comment by jnicholls** [comment]
That sounds good, and isn't sacrificing much ergonomics in the end.
