### ISSUE TITLE
Feature request: try_sync

### ISSUE THREAD

**Issue by FredrikNoren** [bcndanos/asynchronous#3]
Hi,

Looks like a cool library, only have one small feature request: a non blocking try_sync that returns a value if there is one and None otherwise.

**Comment by bcndanos** [comment]
You can use the "finally" method to catch the value returned by a Promise. It's non blocking(Runs in another thread)

asynchronous::Promise::new(|| {
   ....
   Ok(Some("value"));  // or Ok(None);
}).finally(|res| { 
   // res here is an Option<&str>
});

Perhaps is that what you need?

**Comment by FredrikNoren** [comment]
Hm but I wouldn't be able to access my other outside state from there right? My use case is loading resource in a program with a main loop, where I don't want to block the main loop, but once the resource is loaded I want to put it in the right place etc.

**Comment by bcndanos** [comment]
Ok, I see what you mean. 
I think that you have to catch the event for "ResourceLoaded" into your event-loop.

For example, assuming your current event loop looks like this:

```
let (tx,rx) = mpsc::channel();
let resource = None;
look_up_resource_in_async(tx.clone());
loop {
   let event = rx.recv().unwrap();
   math event {
      Your other events => Your code ....,
      CustomEvent::ResourceLoaded(r) => resource = Some(r)
   }
}

fn look_up_resource_in_async(tx:mpsc::Receiver<CustomEvent>) {
   asynchronous::Promise::new(|| {      
       let resource =  // your blocking code to look up the resource
       Ok(CustomEvent::ResouceLoaded(resource))
   }).finally(|res| { 
      // res here is a CustomEvent
      tx.send(res);
   });
}
```

I haven't tested the code above, but this is the main idea.

**Comment by FredrikNoren** [comment]
Ok cool, I guess that could work
